### ISSUE TITLE
Inefficient use of hardware layers

### ISSUE THREAD

**Issue by evant** [IFTTT/SparkleMotion#43]
Steps to reproduce:
1. Go to developer options and turn on "Show hardware layers updates"
2. Open sample app and swipe between pages 
3. Notice the whole screen is constantly green

Hardware layers are efficient to animate but expensive to create. You should only create them when the content itself is not changing on a page while paging. Unfortunately, viewpager does this by itself with no easy way to turn it off. You can work around it by disabling the hardware layer in `onPageScrollStateChanged(int state)` when scrolling starts. Strangely enough, I still see the green on the alpha and scale animation demos (these should be fine since the content of the page isn't changing). Zoom Out in the demo is the only one that seems to be behaving correctly in this regard. Using the similar examples [from the android documentation](http://developer.android.com/intl/zh-cn/training/animation/screen-slide.html) do not exhibit the same behavior.

**Comment by lzanita09** [comment]
Indeed, ViewPager uses hardware layer for its child Views when PageTransformer is used, which is the case for Sparkle Motion. By setting it back to `LAYER_TYPE_NONE` for the page View and set hardware layer to the View being animated seems to make things a lot better.

The reason that only zoom out animation demo didn't have the issue is that the zoom out animation is animating the page View (one of the child Views in ViewPager), while the other demos are animating a specific View within the page.
